### ISSUE TITLE
html, body properties in style.css

### ISSUE THREAD

**Issue by bmonaumann** [labadserver/Adplayer#5]
The following part in **style.css** should be removed from this file, because this property is demo specific and can cause problems on live websites. Maybe move this part to an inline stylesheet in **demo/index.html**.

``` css
body, html {
  font-family: 'Arial'; 
}
```

The font properties for **.privacyButton .text** should be fixed.
